routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::resource('articles' , 'ArticlesController');
//Route::middleware('auth')->group(function(){
//	Route::resource('articles' , 'ArticlesController');
Route::resource('users' , 'UserController');
Route::resource('roles' , 'RoleController');
Route::resource('permissions' , 'PermissionController');


//});
Route::get('blog' , 'AboutController@showblog');
Route::get('about' , 'AboutController@about');
Route::get('contact' , 'AboutController@contact');
// Route::get('articles' , 'ArticlesController@index');
// Route::post('articles' , 'ArticlesController@store');
// Route::get('articles/create' , 'ArticlesController@create');
// Route::get('articles/{id}' , 'ArticlesController@show');
// Route::delete('articles/{id}' , 'ArticlesController@destroy');
Route::get('/home' , 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function article()
    {
        return $this->hasMany('App\Article');
    }
    public function role()
    {
        return $this->belongsTo('App\Role');
    }
    public function permission()
    {
        return $this->belongsToMany('App\Permission');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Permission;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::all();

        return view ('users.index' , compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = Role::get();
        return view('users.create' , compact('roles'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , ['name' =>'required' ,
            'email'=>'required' ,
            'password' =>'required' ,
            'roles' => 'required'
        ]);
        $users = User::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::findOrFail($id);
        $roles = Role::get();
        return view('user.edit' , compact('users' , 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin')

@section('style')
@endsection

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        داشبرد اموات
    </h1>
</section>
<!-- Main content -->
<section class="content">
    @include('layouts.sections.messages')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">ایجاد کاربر</h3>
                </div>
              <!-- /.box-header -->
                <form action="{{ route('users.store') }}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name">نام</label>
                            <input type="text" name="name" class="form-control" value="{{ old('name') }}" id="name" placeholder="نام">
                            @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email">ایمیل</label>
                            <input type="text" name="email" class="form-control" value="{{ old('email') }}" id="email" placeholder="ایمیل">
                            @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('mobile') ? ' has-error' : '' }}">
                            <label for="mobile">موبایل</label>
                            <input type="text" name="mobile" class="form-control" value="{{ old('mobile') }}" id="mobile" placeholder="موبایل">
                            @if ($errors->has('mobile'))
                            <span class="help-block">
                                <strong>{{ $errors->first('mobile') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password">رمزعبور</label>
                            <input type="text" name="password" class="form-control" value="{{ old('password') }}" id="password" placeholder="رمزعبور">
                            @if ($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                        
                    <!-- ./box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">ثبت</button>
                    </div>
                </form>
            <!-- /.box-footer -->
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection

@section('js')
@endsection

resources/views/users/edit.blade.php
@extends('layouts.admin')

@section('style')
@endsection

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        داشبرد اموات
    </h1>
</section>
<!-- Main content -->
<section class="content">
    @include('layouts.sections.messages')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">ویرایش نقش</h3>
                </div>
                <!-- /.box-header -->
                <form action="{{ route('users.update', ['id' => $user->id]) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name">نام</label>
                            <input type="text" name="name" class="form-control" value="{{ $user->name }}" id="name" placeholder="نام">
                            @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email">ایمیل</label>
                            <input type="text" name="email" class="form-control" value="{{ $user->email }}" id="email" placeholder="ایمیل">
                            @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('mobile') ? ' has-error' : '' }}">
                            <label for="mobile">موبایل</label>
                            <input type="text" name="mobile" class="form-control" value="{{ $user->mobile }}" id="mobile" placeholder="موبایل">
                            @if ($errors->has('mobile'))
                            <span class="help-block">
                                <strong>{{ $errors->first('mobile') }}</strong>
                            </span>
                            @endif
                        </div>
                        {{-- <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password">رمزعبور</label>
                            <input type="text" name="password" class="form-control" value="" id="password" placeholder="رمزعبور">
                            @if ($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                            @endif
                        </div> --}}
                        <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                            <label for="roles">نقش</label>
                            @php
                                $users_role = $user->roles->first();
                            @endphp
                            <select name="role" class="form-control">
                                <option disabled="" selected="">انتخاب کنید</option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}" @if($users_role and $users_role->id == $role->id ) selected="" @endif>{{ $role->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('roles'))
                            <span class="help-block">
                                <strong>{{ $errors->first('roles') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                    <!-- ./box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">ثبت</button>
                    </div>
                </form>
            </div>
    <!-- /.box -->
        </div>
    <!-- /.col -->
    </div>
<!-- /.row -->
</section>
<!-- /.content -->
@endsection

@section('js')
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin')

@section('style')
@endsection

@section('modal')
<!-- Modal -->
    @can('users-destroy')
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form action="#" id="delete_frm" method="post">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">دقت نمایید</h4>
                        </div>
                        <div class="modal-body">

                            @csrf
                            @method('DELETE')
                            <div class="form-group">
                                <label for="description">آیا اطمینان دارید که می‌خواهید کاربر را پاک کنید؟</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
                            <button type="submit" class="btn btn-primary">تایید</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcan
@endsection

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    داشبرد اموات
</h1>
</section>
<!-- Main content -->
<section class="content">
    @include('layouts.sections.messages')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">نمایش کاربران</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            @can('users-store')
                <a href="{{ route('users.create') }}" class="btn btn-success" style="margin-bottom: 10px" >افزودن</a>
            @endcan
            <table class="table table-bordered">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>نام</th>
                    <th>موبایل</th>
                    <th>ایمیل</th>
                    <th>نقش</th>
                    <th>عملیات</th>
                </tr>
                @foreach($users as $user)
                <tr>
                    
                    <td>{{$user->name}}</td>
                    <td>{{$user->mobile}}</td>
                    <td>{{$user->email}}</td>
                    
                    <td>
                        @can('users-update')
                            <a href="{{ route('users.edit', ['id'=> $user->id]) }}">ویرایش</a>
                        @endcan

                        @can('users-destroy')
                             | <a href="#" class="delete_btn" data-toggle="modal" data-action="{{ route('users.destroy', ['id' => $user->id]) }}" data-target="#myModal" >حذف</a>
                        @endcan
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
        <!-- ./box-body -->
        <div class="box-footer clearfix">
          
      </div>
      <!-- /.box-footer -->
  </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->
</section>
<!-- /.content -->
@endsection

@section('js')
    <script>
        $('.delete_btn').on('click', function()
        {
            action = $(this).data('action');
            $('#delete_frm').attr('action',action);
        })
    </script>
@endsection